// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import GeolocationController from "./geolocation_controller"
application.register("geolocation", GeolocationController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LiveController from "./live_controller"
application.register("live", LiveController)

import MapController from "./map_controller"
application.register("map", MapController)

import MergemapsController from "./mergemaps_controller"
application.register("mergemaps", MergemapsController)

import PlayController from "./play_controller"
application.register("play", PlayController)

import WaterController from "./water_controller"
application.register("water", WaterController)

import WeatherController from "./weather_controller"
application.register("weather", WeatherController)
