// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import LiveController from "./live_controller"
application.register("live", LiveController)

import MergemapsController from "./mergemaps_controller"
application.register("mergemaps", MergemapsController)

import WeatherController from "./weather_controller"
application.register("weather", WeatherController)
